version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
     - .:/application
     - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"

  php-fpm:
    image: php:fpm-alpine
    container_name: php-fpm
    working_dir: /application
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/application
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - ./api:/app
